### ISSUE TITLE
Is this loader workable ?

### ISSUE THREAD

**Issue by zzswang** [javiercf/react-markdown-loader#8]
Just had a try, seems not work properly.

**Comment by javiercf** [comment]
It's part of our current build process and is working as intended right now, could you post some code or logs to see what you are currently having issues with and how we can help you?

**Comment by zzswang** [comment]
Thanks a lot.

I've set it up now.  I find there some errors in README.md, May be a pull request could explain it :)

I really find code in this repo is in high quality. Like it.
